### ISSUE TITLE
Using insecure random number generator

### ISSUE THREAD

**Issue by ghost** [neoKushan/BCrypt.Net-Core#1]
Your version:

```
Random rng = new Random();
rng.NextBytes(rnd);
```

Original version:

```
RandomNumberGenerator rng = RandomNumberGenerator.Create();
rng.GetBytes(rnd);
```

The original's random number generator is derived from System.Security.Cryptography and designed to be used with cryptographic algorithms, whereas your drop in replacement seems to be using the insecure (albeit faster) Random class. 

Not sure it is safe to use this for cryptographic purposes currently, but appreciate the attempt to port over! :-) I'll submit a pull request to implement the secure random generator if I get time.

**Comment by neoKushan** [comment]
@liamsymonds you're absolutely correct, this was a bit of a bone-headed error on my part! I need to port the library to the RC2 bits and target netstandard anyway, so I'll fix it while I'm doing that. Thanks for the heads up!

**Comment by neoKushan** [comment]
I've fixed this with the update to RC2 / Targeting of Netstandard. 1.0.2 has been pushed to Nuget.
