### ISSUE TITLE
Prevent timing attack by constant-time hash comparison

### ISSUE THREAD

**Issue by arnebit** [neoKushan/BCrypt.Net-Core#3]
There's [a pull request at the original BCrypt project](https://bcrypt.codeplex.com/SourceControl/network/forks/the_dusky/BCryptNet/contribution/5976#!/tab/changes) that prevents a (possibly not terribly dangerous) timing attack that has never been merged, which [is a shame, as one commenter there noted](https://bcrypt.codeplex.com/discussions/651291).

Any chance of incorporating the fix here?

**Comment by neoKushan** [comment]
Yes, there's definitely scope for doing this. When I get some free time, I'm going to finish converting the project to the final SDK project. I'll look through the pull requests on codeplex and pick out any that are relevant (and portable to core).

**Comment by neoKushan** [comment]
I've added the safe compare code to the project and released 1.3.0 to Nuget.
