### ISSUE TITLE
Question: Signed version of this NuGet package

### ISSUE THREAD

**Issue by dfarrNTST** [neoKushan/BCrypt.Net-Core#5]
Sorry to have to ask this, we have some legacy system that would love to use this, but they require signed assemblies and we are unable to use this NuGet package with those applications.  Do you have a signed version of this NuGet package?

Thanks

**Comment by neoKushan** [comment]
Yeah you should be sorry! 😛 

Nah it's all right, I knew this day would come eventually. v1.4.0 has been [pushed to Nuget](https://www.nuget.org/packages/BCrypt.Net-Core/1.4.0), same as 1.3.0 but now strong named/signed.

Enoy!

I'll leave this issue open for a couple of days, let me know if it works for you and I'll close it.

**Comment by dfarrNTST** [comment]
Wow...thanks for the quick response.  Is it a pain to create a "BCrypt.Net-Core" unsigned version and a "BCrypt.Net-Core-Signed" version so both exist out in NuGet?  This is probably what I'll need to do with my libraries having 2 projects, 1 for signed and 1 for unsigned, but both available in NuGet.

Only reason I ask is I'm not sure if we can use a signed assembly in an unsigned project.  Our standard is to never sign our assemblies, but we got the old folks using old apps that need it.

I promise I won't ask for anything else!  ;)

**Comment by neoKushan** [comment]
Hello @dfarrNTST,

I've pondered and pondered over this and the general feel of the community seems to be to move towards strong naming the package and dumping non-strong-named packages. I don't particularly want to maintain two different packages for the sake of this, so I'm afraid I'm going to leave this as strong named for now. 

Feel free to fork this if you like to create your own non-strong-named package, with my blessing.
