### ISSUE TITLE
Package downgrade error when using with .NET Core 2.1

### ISSUE THREAD

**Issue by modo-lv** [neoKushan/BCrypt.Net-Core#7]
Installing the package into a .NET Core 2.1 project fails:

    Installing BCrypt.Net-Core 1.4.0.
    NU1605: Detected package downgrade: System.Runtime.Extensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
     MoCat.Core -> BCrypt.Net-Core 1.4.0 -> NETStandard.Library 1.6.1 -> System.Runtime.Extensions (>= 4.3.0) 
     MoCat.Core -> BCrypt.Net-Core 1.4.0 -> System.Runtime.Extensions (>= 4.1.0)
    Package restore failed. Rolling back package changes for 'MoCat.Core'.

Direct referencing workaround does work, but an update would make for a smoother install.

**Comment by neoKushan** [comment]
Good spot, I'll see if I can get this fixed in the next day or two.

**Comment by neoKushan** [comment]
Sorry this took a bit longer to get around to than I anticipated, but I've uploaded v1.5.0 to Nuget which fixes this issue. Let me know if you have any issues with it.
