### ISSUE TITLE
Is there a way to get work factor from hashed password? 

### ISSUE THREAD

**Issue by SureshAmudalapalli** [neoKushan/BCrypt.Net-Core#9]
Hi,

It would be helpful if we add an utility that returns work factor from a hashed password as input. 

Thanks,
Suresh

**Comment by neoKushan** [comment]
Hi @SureshAmudalapalli ,

There isn't a way to get the work factor from the library, but it's pretty trivial if you wanted to do it yourself. Taking the following example:

`$2b$06$DCq7YPn5Rq63x1Lad4cll.TV4S6ytwfsfvkgY8jIucDrjc8deX1s.`

The work factor is 06, it will always be the value at that index after the second $. You can retrieve that in a number of ways, here's where it gets done in the library itself:  https://github.com/neoKushan/BCrypt.Net-Core/blob/4b6869832512e3aba68e31979ee4af5d19397ac2/src/BCrypt.Net-Core/BCrypt.cs#L468

(Note that in this case the starting offset is set to `4`).

For a naive implimentation, you can simply call `hash.Substring(4,2);`

**Comment by SureshAmudalapalli** [comment]
Yeah, it's a small change but we have to run some validations before expecting `hash.Substring(4,2);` would return correct work factor from a hashed password.

**Comment by neoKushan** [comment]
Sorry @SureshAmudalapalli, I'm not clear on exactly what it is you're trying to achieve. Could you elaborate further? What is it you're doing with the work factor that you need to extract it?

I _could_ add a method to return the work factor, but if you pass in an invalid hash then what would you expect the behaviour of the library to be? I'd end up throwing a SaltParseException so you'd have to validate it in some way anyway (or handle the exceptions).

I'm reluctant to add such a method to the library as I don't understand the usecase and why you need to know. In my simple view, you either want to create a hash or validate one - the internals of that hash shouldn't really be of any concern. If you can elaborate your use-case further, I'd be happy to consider it.

In the meantime, perhaps this extension class will help you?

https://gist.github.com/neoKushan/0f37c6d5d79bb4c514f679043dd712d2

**Comment by SureshAmudalapalli** [comment]
In general, the work factor which is used to Bcrypt should be changed based on processing time. We have to calculate the number of rounds based on password verification on the server. And in my use case, I want to check the existing hashed work factor and then re-hash the password whenever we change work factor. 

Please take a look at this PR: https://github.com/neoKushan/BCrypt.Net-Core/pull/10 

And let me know if you have any feedback.

**Comment by neoKushan** [comment]
Thanks, I actually agree that's a valid use-case. I am considering if it would be worth adding a rudimentary benchmark method to calculate a reasonable work factor for you (such as by specifying a minimum processing time). 

I do have some comments on your PR that'll need addressing before I can merge it in, however.

**Comment by neoKushan** [comment]
I've merged your PR along with a few minor other changes, v 1.6.0 is now live on Nuget. Let me know if you have any issues!
